[package]
name = "nn"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
license-file = "LICENSE"
description = "Rust library for neural network creation"
repository = "https://github.com/stalker57241/nn-rust"
authors = ["stalker57241 <stalker3204@yandex.ru>"]
keywords = ["neural-network", "feed-forward"]
categories = ["artificial-intelligence"]
exclude = ["/mnist"]
publish = false # For now

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
rand = "0.10.3"
