name: Rust

on:
  push:
    branches: [ "general" ]
    paths-ignore: 
      - "/.md"
      - "docs/"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [ "general" ]
    paths-ignore: 
      - "/.md"
      - "docs/"
      - "LICENSE"
      - ".gitignore"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
